// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnrshjgcemuqoveuosuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBucnNoamdjZW11cW92ZXVvc3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDQyNTQsImV4cCI6MjA2Nzk4MDI1NH0.C3AcMrAE-crzvSNOnd0XWbrPCjICgeZK7ussP_wh6O0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});